# Generated by Django 2.2.17 on 2021-01-21 07:34

import uuid

import django_extensions.db.fields.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnotherTestResource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("keycloak_data", django_extensions.db.fields.json.JSONField(default={"groups": {}})),
                ("title", models.CharField(max_length=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TestResource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("keycloak_data", django_extensions.db.fields.json.JSONField(default={"groups": {}})),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
